### ISSUE TITLE
Getting an error after installing running npm run dev

### ISSUE THREAD

**Issue by dtlevin** [marcamos/jet#33]
I downloaded the project ran "npm i" then "npm run dev" and got this 

`dan.levin@Dan-Levins-MacBook-Pro-2 jet-master % npm run dev

> jet@2.0.0 dev /Users/dan.levin/Sites/jet-master
> npm run clean && postcss src/css/tailwind.css > src/css/styles.css && eleventy --serve

> jet@2.0.0 clean /Users/dan.levin/Sites/jet-master
> rm -rf public src/css/styles.css

TypeError: Object.entries(...).flatMap is not a function
    at flattenColorPalette (/Users/dan.levin/Sites/jet-master/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:83)
    at /Users/dan.levin/Sites/jet-master/node_modules/tailwindcss/lib/plugins/divideColor.js:27:53
    at plugins.forEach.plugin (/Users/dan.levin/Sites/jet-master/node_modules/tailwindcss/lib/util/processPlugins.js:69:5)
    at Array.forEach (<anonymous>)
    at _default (/Users/dan.levin/Sites/jet-master/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /Users/dan.levin/Sites/jet-master/node_modules/tailwindcss/lib/processTailwindFeatures.js:60:54
    at LazyResult.runOnRoot (/Users/dan.levin/Sites/jet-master/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/Users/dan.levin/Sites/jet-master/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/Users/dan.levin/Sites/jet-master/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/Users/dan.levin/Sites/jet-master/node_modules/postcss/lib/lazy-result.js:190:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jet@2.0.0 dev: `npm run clean && postcss src/css/tailwind.css > src/css/styles.css && eleventy --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jet@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by dtlevin** [comment]
Just tested all of the releases and it breaks on the tailwind 2.0 update if that helps. Still looking for a fix.

**Comment by dtlevin** [comment]
Never mind it was a node issue.

**Comment by marcamos** [comment]
Yeah, I think `flatMap` was introduced in Node v11; glad you got it sorted, @dtlevin!
